---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: products
    labels:
        app: products
spec:
    replicas: 2
    selector:
        matchLabels:
            app: products
    revisionHistoryLimit: 5
    minReadySeconds: 10
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 2
            maxUnavailable: 0
    template:
        metadata:
            labels:
                app: products
        spec:
            containers:
                - name: products
                  image: gcr.io/just-strength-233319/github_kuberton_products:latest
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 8080
                        protocol: TCP
                  # readinessProbe:
                  #     httpGet:
                  #         path: /health
                  #         port: 8080
                  #     initialDelaySeconds: 10
                  #     periodSeconds: 10
                  #     timeoutSeconds: 5
                  # livenessProbe:
                  #     httpGet:
                  #         path: /health
                  #         port: 8080
                  #     initialDelaySeconds: 10
                  #     periodSeconds: 10
                  #     timeoutSeconds: 5
                  resources:
                      limits:
                          memory: '528M'
            dnsPolicy: ClusterFirst
            restartPolicy: Always
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: products
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: products
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80
---
apiVersion: v1
kind: Service
metadata:
  name: products
  labels:
    app: products
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: products
  type: LoadBalancer
  # loadBalancerIP: 34.76.106.184
  sessionAffinity: ClientIP